spring:
  application:
    name: mscloudgateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # <- Habilitando o localizador
          lower-case-service-id: true # <- Informando para procurar os micro servi?os configurados na fun??o main em lowercase (letras min?sculas)

server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
